name             'rbdswatcher'
maintainer       'Eneo Tecnología S.L.'
maintainer_email 'git@redborder.com'
license          'AGPL-3.0'
description      'Installs/Configures cookbook-dswatcher'
version          '1.0.0'
